### ISSUE TITLE
Preview panel does not appear, but everything else works

### ISSUE THREAD

**Issue by xxx** [ldenisey/idea-openscad#33]
**Describe the bug**
I am unable to find any way to preview the model within Idea. All other functionality that I've tested works (e.g. Export as... & Render This File). Openscad is correctly found by the plugin on my system.

**To Reproduce**
Install the plugin and open a scad file.

**Code snippet**
affects all scad files.

**Expected behavior**
There's some way for me to preview the model within Idea.

**Screenshots**
![image](https://user-images.githubusercontent.com/41678/184812493-7fc0177d-a7f9-44ce-8f84-d85a332145e8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Ubuntu 22.04
 - Jetbrains platform and version: [e.g. IntelliJ community  2022.1.3] Idea Ultimate 2022.2
 - OpenSCAD plugin version: Version [e.g. 2.2.0] 2.2.0

**Additional context**
I feel like I'm missing something, but the documentation only says

> The preview panel is available if OpenSCAD is installed on your machine.

which it totally is, and the plugin knows it.

**Comment by ldenisey** [comment]
Hello,

Is it a first installation of the plugin or is it an update from previous version ?
Also, can you confirm the checkbox "Allow preview editor" is checked in Settings -> Languages & Frameworks -> OpenSCAD ?

**Comment by xxx** [comment]
Heya, thanks for responding.

This is a first-time installation.

I don't see the checkbox you mention in my settings, though - 

![image](https://user-images.githubusercontent.com/41678/185481185-92b4f24b-4151-486d-ac15-2408975d2f6a.png)

**Comment by xxx** [comment]
ack, I just updated the plugin to version 2.3.0. That resolves this issue and it's working great now.

**Comment by ldenisey** [comment]
Good to hear. For information, this version is quite a big one, don't hesitate to report other issues you might encounter.
