### ISSUE TITLE
Add support for exponent operator

### ISSUE THREAD

**Issue by degroof** [ldenisey/idea-openscad#36]
Currently indicates syntax error for exponent operator (e.g. x^y):

`OpenSCADTokenType.EQUALS or OpenSCADTokenType.LPARENTH expected, got '^'`

**Comment by ldenisey** [comment]
Adding in https://github.com/ldenisey/idea-openscad/commit/4f0ee15242f5646ade05d6770cba6879ec497ce6, will be released soon.

**Comment by ldenisey** [comment]
Released in 2.3.2 which is currently under review by Jetbrains team before public release. Should be available within 2 days.
