### ISSUE TITLE
Bug: parsing of multi-line comment ending with 2 stars

### ISSUE THREAD

**Issue by yannickbattail** [ldenisey/idea-openscad#72]
**Describe the bug**
a multi-line comment ending with 2 stars appears as an error

**To Reproduce**
create a file with content:
```openscad
/* **/
```

**Expected behavior**
a multi-line comment ending with 2 stars should not appear as an error.

**Desktop (please complete the following information):**
 - OS: linux ubuntu 22.10
 - Jetbrains platform and version: JetBrains Rider 2022.3.2
 - OpenSCAD plugin version: 2.3.3

**Comment by ldenisey** [comment]
Thanks for reporting, fixed in #104.
