### ISSUE TITLE
Keyboard shortcut to refresh preview

### ISSUE THREAD

**Issue by olivbd** [ldenisey/idea-openscad#81]
**Is your feature request related to a problem? Please describe.**
Switching between keyboard to code and mouse to click on "Refresh Preview" button isn't very useful!
In my IDE settings (IntelliJ IDEA), there is no keymap named "OpenSCAD Refresh Preview", so I'm unable to set a keyboard shortcut.

**Describe the solution you'd like**
I'd like to get a customizable keyboard shortcut to refresh the preview while I'm coding.

**Describe alternatives you've considered**
No alternatives found.

**Additional context**
In OpenSCAD GUI you have also a keyboard shortcut to do this (F5)

**Comment by Kernald** [comment]
Even more than that, an option to auto-refresh the preview on file save would be fantastic.

**Comment by ldenisey** [comment]
@olivbd, I have added the refresh action in the keymap list. It will be released soon.
@Kernald, why not, can you make a dedicated issue for that ?

**Comment by Kernald** [comment]
Done in #99 - thanks!

**Comment by ldenisey** [comment]
Done in #100
