### ISSUE TITLE
Maintain viewport on preview refresh

### ISSUE THREAD

**Issue by Kernald** [ldenisey/idea-openscad#83]
**Is your feature request related to a problem? Please describe.**
Resetting the viewport on preview refresh adds quite a bit of friction.

**Describe the solution you'd like**
Keeping the previous viewport on refresh would be ideal. An intermediate, maybe much simpler solution would be allowing to set a different default viewport - the current default is not ideal.

**Describe alternatives you've considered**
The only alternative is to move the viewport manually with the mouse.

**Additional context**
n/a

**Comment by ldenisey** [comment]
Thank you for your issue, it has been changed in #98 and will be released soon.
