### ISSUE TITLE
Auto-refresh preview on file save

### ISSUE THREAD

**Issue by Kernald** [ldenisey/idea-openscad#99]
**Is your feature request related to a problem? Please describe.**
This would help iterating quickly. Related to #81, currently, refreshing the preview is not super straightforward to do while working on the model at the same time. #81 soon being fixed will get us most of the way there, but auto-refreshing on file save would be even quicker. It would also match what a lot of instant reload style tools are doing.

**Describe the solution you'd like**
An option (the ability to be disabled probably matters for large models) to enable/disable auto-refresh on file save.

**Describe alternatives you've considered**
Clicking on the refresh button, which works but isn't super smooth.

**Additional context**

**Comment by ldenisey** [comment]
Will be done in #101
